steps:
    -   name: 'gcr.io/cloud-builders/docker'
        args: [ 'build', '-t', 'gcr.io/m-app-3/hdyf_admin:$COMMIT_SHA', '.' ]
        timeout: 600s
    # Push the image to Container Registry
    -   name: 'gcr.io/cloud-builders/docker'
        args: ['push', 'gcr.io/m-app-3/hdyf_admin:$COMMIT_SHA']
        timeout: 600s
    -   name: "gcr.io/cloud-builders/gcloud"
        args:
            - 'run'
            - 'deploy'
            - 'hdyf-admin'
            - '--image'
            - 'gcr.io/m-app-3/hdyf_admin:$COMMIT_SHA'
            - '--region'
            - 'us-central'
            - '--platform'
            - 'managed'
        timeout: 600s
images:
    - gcr.io/m-app-3/hdyf_admin