FROM node:12.16-alpine

RUN mkdir -p /usr/src

RUN mkdir -p /app

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn

EXPOSE 8080

ADD entrypoint-prod.sh /usr/src/

ENTRYPOINT /usr/src/entrypoint-prod.sh
